=== friedger/stacks-blockchain-sidecar/docs/api/transaction/get-transactions.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "GET request that returns transactions",
  "title": "TransactionResults",
  "type": "object",
  "required": ["results", "limit", "offset", "total"],
  "properties": {
    "limit": {
      "type": "integer"
    },
    "offset": {
      "type": "integer"
    },
    "total": {
      "type": "integer"
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "../../entities/transactions/transaction.schema.json"
      }
    }
  }
}

=== friedger/stacks-blockchain-sidecar/docs/api/transaction/get-transactions.example.json
{
  "limit": 10,
  "offset": 0,
  "total": 101922,
  "results": [
    {
      "block_hash": "0x354b5e87fe7f749fb2a635a36d4a2b0cae6f380c740ceaf908ce9dab1e661a60",
      "block_height": 18,
      "canonical": true,
      "tx_id": "0xf19099a7f3ead7a89e952fa3297f021691f05d4bbbc86e702cef385116a6e6f4",
      "tx_index": 0,
      "tx_status": "success",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST2ZHNQT5J12DZBMSYN82X8NE73XXJSADZ2JPDY6M",
      "sponsored": false,
      "post_condition_mode": "allow",
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  ]
}
